<?php

namespace Database\Seeders;

use App\Models\Condition;
use App\Models\ConditionFilter;
use App\Models\Filter;
use Illuminate\Database\Seeder;

class FilterTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Filter::truncate();
        ConditionFilter::truncate();
        $filtersJson = [
            "Countries" =>  [
                [
                    "name" => "United States and Canada ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "US-CA",
                    "query" => "",
                    "value" => "1",
                ],
                [
                    "name" => "Afghanistan ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "AF",
                    "query" => "",
                    "value" => "93",
                ],
                [
                    "name" => "Albania ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "AL",
                    "query" => "",
                    "value" => "355",
                ],
                [
                    "name" => "Algeria ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "DZ",
                    "query" => "",
                    "value" => "213",
                ],
                [
                    "name" => "American Samoa",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "AS",
                    "query" => "",
                    "value" => "1684",
                ],
                [
                    "name" => "Andorra",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "AD",
                    "query" => "",
                    "value" => "376",
                ],
                [
                    "name" => "Angola",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "AO",
                    "query" => "",
                    "value" => "244",
                ],
                [
                    "name" => "Anguilla ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "AI",
                    "query" => "",
                    "value" => "1264",
                ],
                [
                    "name" => "Antarctica Norfolk Island",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "AQ-NF",
                    "query" => "",
                    "value" => "672",
                ],
                [
                    "name" => "Antigua and Barbuda",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "AG",
                    "query" => "",
                    "value" => "1268",
                ],
                [
                    "name" => "Argentina ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "AR",
                    "query" => "",
                    "value" => "54",
                ],
                [
                    "name" => "Armenia",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "AM",
                    "query" => "",
                    "value" => "374",
                ],
                [
                    "name" => "Aruba",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "AW",
                    "query" => "",
                    "value" => "297",
                ],
                [
                    "name" => "Australia",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "AU",
                    "query" => "",
                    "value" => "61",
                ],
                [
                    "name" => "Austria",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "AT",
                    "query" => "",
                    "value" => "43",
                ],
                [
                    "name" => "Azerbaijan or Azerbaidjan",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "AZ",
                    "query" => "",
                    "value" => "994",
                ],
                [
                    "name" => "Bahamas",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "BS",
                    "query" => "",
                    "value" => "1242",
                ],
                [
                    "name" => "Bahrain",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "BH",
                    "query" => "",
                    "value" => "973",
                ],
                [
                    "name" => "Bangladesh",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "BD",
                    "query" => "",
                    "value" => "880",
                ],
                [
                    "name" => "Barbados ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "BB",
                    "query" => "",
                    "value" => "1246",
                ],
                [
                    "name" => "Belarus",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "BY",
                    "query" => "",
                    "value" => "375",
                ],
                [
                    "name" => "Belgium ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "BE",
                    "query" => "",
                    "value" => "32",
                ],
                [
                    "name" => "Belize ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "BZ",
                    "query" => "",
                    "value" => "501",
                ],
                [
                    "name" => "Benin",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "BJ",
                    "query" => "",
                    "value" => "229",
                ],
                [
                    "name" => "Bermuda ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "BM",
                    "query" => "",
                    "value" => "1441",
                ],
                [
                    "name" => "Bhutan",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "BT",
                    "query" => "",
                    "value" => "975",
                ],
                [
                    "name" => "Bolivia ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "BO",
                    "query" => "",
                    "value" => "591",
                ],
                [
                    "name" => "Bosnia and Herzegovina ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "BA",
                    "query" => "",
                    "value" => "387",
                ],
                [
                    "name" => "Botswana",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "BW",
                    "query" => "",
                    "value" => "267",
                ],
                [
                    "name" => "Brazil ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "BR",
                    "query" => "",
                    "value" => "55",
                ],
                [
                    "name" => "Brunei ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "BN",
                    "query" => "",
                    "value" => "673",
                ],
                [
                    "name" => "Bulgaria ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "BG",
                    "query" => "",
                    "value" => "359",
                ],
                [
                    "name" => "Burkina Faso ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "BF",
                    "query" => "",
                    "value" => "226",
                ],
                [
                    "name" => "Burundi ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "BI",
                    "query" => "",
                    "value" => "257",
                ],
                [
                    "name" => "Cambodia",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "KH",
                    "query" => "",
                    "value" => "855",
                ],
                [
                    "name" => "Cameroon ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "CM",
                    "query" => "",
                    "value" => "237",
                ],
                [
                    "name" => "Cape Verde ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "CV",
                    "query" => "",
                    "value" => "238",
                ],
                [
                    "name" => "Cayman Islands ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "KY",
                    "query" => "",
                    "value" => "1345",
                ],
                [
                    "name" => "Central African Republic ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "CF",
                    "query" => "",
                    "value" => "236",
                ],
                [
                    "name" => "Chad ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "TD",
                    "query" => "",
                    "value" => "235",
                ],
                [
                    "name" => "Chile ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "CL",
                    "query" => "",
                    "value" => "56",
                ],
                [
                    "name" => "China ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "CN",
                    "query" => "",
                    "value" => "86",
                ],
                [
                    "name" => "Christmas Island ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "CX",
                    "query" => "",
                    "value" => "53",
                ],
                [
                    "name" => "Cocos (Keeling) Islands ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "CC",
                    "query" => "",
                    "value" => "61",
                ],
                [
                    "name" => "Colombia ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "CO",
                    "query" => "",
                    "value" => "57",
                ],
                [
                    "name" => "Comoros and Mayotte",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "KM-YT",
                    "query" => "",
                    "value" => "269",
                ],
                [
                    "name" => "Congo, Democratic Republic of the",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "CD",
                    "query" => "",
                    "value" => "243",
                ],
                [
                    "name" => "Congo, Republic of the",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "CG",
                    "query" => "",
                    "value" => "242",
                ],
                [
                    "name" => "Cook Islands",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "CK",
                    "query" => "",
                    "value" => "682",
                ],
                [
                    "name" => "Costa Rica ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "CR",
                    "query" => "",
                    "value" => "506",
                ],
                [
                    "name" => "Cote D\'Ivoire ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "CI",
                    "query" => "",
                    "value" => "225",
                ],
                [
                    "name" => "Croatia ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "HR",
                    "query" => "",
                    "value" => "385",
                ],
                [
                    "name" => "Cuba ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "CU",
                    "query" => "",
                    "value" => "53",
                ],
                [
                    "name" => "Cyprus ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "CY",
                    "query" => "",
                    "value" => "357",
                ],
                [
                    "name" => "Czech Republic",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "CZ",
                    "query" => "",
                    "value" => "420",
                ],
                [
                    "name" => "Denmark ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "DK",
                    "query" => "",
                    "value" => "45",
                ],
                [
                    "name" => "Djibouti",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "DJ",
                    "query" => "",
                    "value" => "253",
                ],
                [
                    "name" => "Dominica ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "DM",
                    "query" => "",
                    "value" => "1767",
                ],
                [
                    "name" => "Dominican Republic ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "DO",
                    "query" => "",
                    "value" => "1829",
                ],
                [
                    "name" => "Dominican Republic ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "DO",
                    "query" => "",
                    "value" => "1809",
                ],
                [
                    "name" => "East Timor ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "TP",
                    "query" => "",
                    "value" => "670",
                ],
                [
                    "name" => "Ecuador ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "EC",
                    "query" => "",
                    "value" => "593 ",
                ],
                [
                    "name" => "Egypt ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "EG",
                    "query" => "",
                    "value" => "20",
                ],
                [
                    "name" => "El Salvador ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "SV",
                    "query" => "",
                    "value" => "503",
                ],
                [
                    "name" => "Equatorial Guinea ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "GQ",
                    "query" => "",
                    "value" => "240",
                ],
                [
                    "name" => "Eritrea ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "ER",
                    "query" => "",
                    "value" => "291",
                ],
                [
                    "name" => "Estonia",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "EE",
                    "query" => "",
                    "value" => "372",
                ],
                [
                    "name" => "Ethiopia ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "ET",
                    "query" => "",
                    "value" => "251",
                ],
                [
                    "name" => "Falkland Islands ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "FK",
                    "query" => "",
                    "value" => "500",
                ],
                [
                    "name" => "Faroe Islands ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "FO",
                    "query" => "",
                    "value" => "298",
                ],
                [
                    "name" => "Fiji ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "FJ",
                    "query" => "",
                    "value" => "679",
                ],
                [
                    "name" => "Finland ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "FI",
                    "query" => "",
                    "value" => "358",
                ],
                [
                    "name" => "France ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "FR",
                    "query" => "",
                    "value" => "33",
                ],
                [
                    "name" => "French Guiana",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "GF",
                    "query" => "",
                    "value" => "594",
                ],
                [
                    "name" => "French Polynesia",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "PF",
                    "query" => "",
                    "value" => "689",
                ],
                [
                    "name" => "Gabon ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "GA",
                    "query" => "",
                    "value" => "241",
                ],
                [
                    "name" => "Gambia, The ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "GM",
                    "query" => "",
                    "value" => "220",
                ],
                [
                    "name" => "Georgia",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "GE",
                    "query" => "",
                    "value" => "995",
                ],
                [
                    "name" => "Germany ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "DE",
                    "query" => "",
                    "value" => "49",
                ],
                [
                    "name" => "Ghana ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "GH",
                    "query" => "",
                    "value" => "233",
                ],
                [
                    "name" => "Gibraltar ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "GI",
                    "query" => "",
                    "value" => "350",
                ],
                [
                    "name" => "Greece ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "GR",
                    "query" => "",
                    "value" => "30",
                ],
                [
                    "name" => "Greenland ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "GL",
                    "query" => "",
                    "value" => "299",
                ],
                [
                    "name" => "Grenada ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "GD",
                    "query" => "",
                    "value" => "1473",
                ],
                [
                    "name" => "Guadeloupe",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "GP",
                    "query" => "",
                    "value" => "590",
                ],
                [
                    "name" => "Guam",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "GU",
                    "query" => "",
                    "value" => "1671",
                ],
                [
                    "name" => "Guatemala ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "GT",
                    "query" => "",
                    "value" => "502",
                ],
                [
                    "name" => "Guinea",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "GN",
                    "query" => "",
                    "value" => "224",
                ],
                [
                    "name" => "Guinea-Bissau ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "GW",
                    "query" => "",
                    "value" => "245",
                ],
                [
                    "name" => "Guyana ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "GY",
                    "query" => "",
                    "value" => "592",
                ],
                [
                    "name" => "Haiti ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "HT",
                    "query" => "",
                    "value" => "509",
                ],
                [
                    "name" => "Honduras ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "HN",
                    "query" => "",
                    "value" => "504",
                ],
                [
                    "name" => "Hong Kong ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "HK",
                    "query" => "",
                    "value" => "852",
                ],
                [
                    "name" => "Hungary ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "HU",
                    "query" => "",
                    "value" => "36",
                ],
                [
                    "name" => "Iceland ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "IS",
                    "query" => "",
                    "value" => "354",
                ],
                [
                    "name" => "India ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "IN",
                    "query" => "",
                    "value" => "91",
                ],
                [
                    "name" => "Indonesia",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "ID",
                    "query" => "",
                    "value" => "62",
                ],
                [
                    "name" => "Iran",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "IR",
                    "query" => "",
                    "value" => "98",
                ],
                [
                    "name" => "Iraq ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "IQ",
                    "query" => "",
                    "value" => "964",
                ],
                [
                    "name" => "Ireland ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "IE",
                    "query" => "",
                    "value" => "353",
                ],
                [
                    "name" => "Israel ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "IL",
                    "query" => "",
                    "value" => "972",
                ],
                [
                    "name" => "Italy ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "IT",
                    "query" => "",
                    "value" => "39",
                ],
                [
                    "name" => "Jamaica ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "JM",
                    "query" => "",
                    "value" => "1876",
                ],
                [
                    "name" => "Japan ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "JP",
                    "query" => "",
                    "value" => "81",
                ],
                [
                    "name" => "Jordan",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "JO",
                    "query" => "",
                    "value" => "962",
                ],
                [
                    "name" => "Kenya ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "KE",
                    "query" => "",
                    "value" => "254",
                ],
                [
                    "name" => "Kiribati",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "KI",
                    "query" => "",
                    "value" => "686",
                ],
                [
                    "name" => "North Korea",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "KP",
                    "query" => "",
                    "value" => "850",
                ],
                [
                    "name" => "South Korea ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "KR",
                    "query" => "",
                    "value" => "82",
                ],
                [
                    "name" => "Kuwait ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "KW",
                    "query" => "",
                    "value" => "965",
                ],
                [
                    "name" => "Kyrgyzstan",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "KG",
                    "query" => "",
                    "value" => "996",
                ],
                [
                    "name" => "Laos",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "LA",
                    "query" => "",
                    "value" => "856",
                ],
                [
                    "name" => "Latvia",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "LV",
                    "query" => "",
                    "value" => "371",
                ],
                [
                    "name" => "Lebanon ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "LB",
                    "query" => "",
                    "value" => "961",
                ],
                [
                    "name" => "Lesotho",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "LS",
                    "query" => "",
                    "value" => "266",
                ],
                [
                    "name" => "Liberia ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "LR",
                    "query" => "",
                    "value" => "231",
                ],
                [
                    "name" => "Libya ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "LY",
                    "query" => "",
                    "value" => "218",
                ],
                [
                    "name" => "Liechtenstein ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "LI",
                    "query" => "",
                    "value" => "423",
                ],
                [
                    "name" => "Lithuania ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "LT",
                    "query" => "",
                    "value" => "370",
                ],
                [
                    "name" => "Luxembourg ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "LU",
                    "query" => "",
                    "value" => "352",
                ],
                [
                    "name" => "Macau ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "MO",
                    "query" => "",
                    "value" => "853",
                ],
                [
                    "name" => "Macedonia",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "MK",
                    "query" => "",
                    "value" => "389",
                ],
                [
                    "name" => "Madagascar ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "MG",
                    "query" => "",
                    "value" => "261",
                ],
                [
                    "name" => "Malawi ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "MW",
                    "query" => "",
                    "value" => "265",
                ],
                [
                    "name" => "Malaysia ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "MY",
                    "query" => "",
                    "value" => "60",
                ],
                [
                    "name" => "Maldives ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "MV",
                    "query" => "",
                    "value" => "960",
                ],
                [
                    "name" => "Mali ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "ML",
                    "query" => "",
                    "value" => "223",
                ],
                [
                    "name" => "Malta ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "MT",
                    "query" => "",
                    "value" => "356",
                ],
                [
                    "name" => "Marshall Islands ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "MH",
                    "query" => "",
                    "value" => "692",
                ],
                [
                    "name" => "Martinique",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "MQ",
                    "query" => "",
                    "value" => "596",
                ],
                [
                    "name" => "Mauritania ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "MR",
                    "query" => "",
                    "value" => "222",
                ],
                [
                    "name" => "Mauritius ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "MU",
                    "query" => "",
                    "value" => "230",
                ],
                [
                    "name" => "Mexico ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "MX",
                    "query" => "",
                    "value" => "52",
                ],
                [
                    "name" => "Micronesia",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "FM",
                    "query" => "",
                    "value" => "691",
                ],
                [
                    "name" => "Moldova",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "MD",
                    "query" => "",
                    "value" => "373",
                ],
                [
                    "name" => "Monaco",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "MC",
                    "query" => "",
                    "value" => "377",
                ],
                [
                    "name" => "Mongolia",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "MN",
                    "query" => "",
                    "value" => "976",
                ],
                [
                    "name" => "Montserrat ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "MS",
                    "query" => "",
                    "value" => "1664",
                ],
                [
                    "name" => "Morocco ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "MA",
                    "query" => "",
                    "value" => "212",
                ],
                [
                    "name" => "Mozambique ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "MZ",
                    "query" => "",
                    "value" => "258",
                ],
                [
                    "name" => "Myanmar",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "MM",
                    "query" => "",
                    "value" => "95",
                ],
                [
                    "name" => "Namibia ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "NA",
                    "query" => "",
                    "value" => "264",
                ],
                [
                    "name" => "Nauru ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "NR",
                    "query" => "",
                    "value" => "674",
                ],
                [
                    "name" => "Nepal ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "NP",
                    "query" => "",
                    "value" => "977",
                ],
                [
                    "name" => "Netherlands ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "NL",
                    "query" => "",
                    "value" => "31",
                ],
                [
                    "name" => "Netherlands Antilles ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "AN",
                    "query" => "",
                    "value" => "599",
                ],
                [
                    "name" => "New Caledonia ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "NC",
                    "query" => "",
                    "value" => "687",
                ],
                [
                    "name" => "New Zealand ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "NZ",
                    "query" => "",
                    "value" => "64",
                ],
                [
                    "name" => "Nicaragua ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "NI",
                    "query" => "",
                    "value" => "505",
                ],
                [
                    "name" => "Niger ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "NE",
                    "query" => "",
                    "value" => "227",
                ],
                [
                    "name" => "Nigeria ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "NG",
                    "query" => "",
                    "value" => "234",
                ],
                [
                    "name" => "Niue",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "NU",
                    "query" => "",
                    "value" => "683",
                ],
                [
                    "name" => "Northern Mariana Islands ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "MP",
                    "query" => "",
                    "value" => "1670",
                ],
                [
                    "name" => "Norway ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "NO",
                    "query" => "",
                    "value" => "47",
                ],
                [
                    "name" => "Oman",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "OM",
                    "query" => "",
                    "value" => "968",
                ],
                [
                    "name" => "Pakistan",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "PK",
                    "query" => "",
                    "value" => "92",
                ],
                [
                    "name" => "Palau ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "PW",
                    "query" => "",
                    "value" => "680",
                ],
                [
                    "name" => "Palestinian State",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "PS",
                    "query" => "",
                    "value" => "970",
                ],
                [
                    "name" => "Panama ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "PA",
                    "query" => "",
                    "value" => "507",
                ],
                [
                    "name" => "Papua New Guinea ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "PG",
                    "query" => "",
                    "value" => "675",
                ],
                [
                    "name" => "Paraguay ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "PY",
                    "query" => "",
                    "value" => "595",
                ],
                [
                    "name" => "Peru ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "PE",
                    "query" => "",
                    "value" => "51",
                ],
                [
                    "name" => "Philippines ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "PH",
                    "query" => "",
                    "value" => "63",
                ],
                [
                    "name" => "Poland ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "PL",
                    "query" => "",
                    "value" => "48",
                ],
                [
                    "name" => "Portugal ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "PT",
                    "query" => "",
                    "value" => "351",
                ],
                [
                    "name" => "Puerto Rico ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "PR",
                    "query" => "",
                    "value" => "1939",
                ],
                [
                    "name" => "Puerto Rico ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "PR",
                    "query" => "",
                    "value" => "1787",
                ],
                [
                    "name" => "Qata",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "QA",
                    "query" => "",
                    "value" => "974 ",
                ],
                [
                    "name" => "Reunion ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "RE",
                    "query" => "",
                    "value" => "262",
                ],
                [
                    "name" => "Romania ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "RO",
                    "query" => "",
                    "value" => "40",
                ],
                [
                    "name" => "Russian Federation and Kazakstan ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "RU-KZ",
                    "query" => "",
                    "value" => "7",
                ],
                [
                    "name" => "Rwanda ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "RW",
                    "query" => "",
                    "value" => "250",
                ],
                [
                    "name" => "Saint Helena ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "SH",
                    "query" => "",
                    "value" => "290",
                ],
                [
                    "name" => "Saint Kitts and Nevis ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "KN",
                    "query" => "",
                    "value" => "1869",
                ],
                [
                    "name" => "Saint Lucia ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "LC",
                    "query" => "",
                    "value" => "1758",
                ],
                [
                    "name" => "Saint Pierre and Miquelon ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "PM",
                    "query" => "",
                    "value" => "508",
                ],
                [
                    "name" => "Saint Vincent and the Grenadines ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "VC",
                    "query" => "",
                    "value" => "1784",
                ],
                [
                    "name" => "Samoa ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "WS",
                    "query" => "",
                    "value" => "685",
                ],
                [
                    "name" => "San Marino ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "SM",
                    "query" => "",
                    "value" => "378",
                ],
                [
                    "name" => "Sao Tome and Principe ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "ST",
                    "query" => "",
                    "value" => "239",
                ],
                [
                    "name" => "Saudi Arabia ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "SA",
                    "query" => "",
                    "value" => "966",
                ],
                [
                    "name" => "Senegal ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "SN",
                    "query" => "",
                    "value" => "221",
                ],
                [
                    "name" => "Seychelles ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "SC",
                    "query" => "",
                    "value" => "248",
                ],
                [
                    "name" => "Sierra Leone ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "SL",
                    "query" => "",
                    "value" => "232",
                ],
                [
                    "name" => "Singapore ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "SG",
                    "query" => "",
                    "value" => "65",
                ],
                [
                    "name" => "Slovakia",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "SK",
                    "query" => "",
                    "value" => "421",
                ],
                [
                    "name" => "Slovenia ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "SI",
                    "query" => "",
                    "value" => "386",
                ],
                [
                    "name" => "Solomon Islands ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "SB",
                    "query" => "",
                    "value" => "677",
                ],
                [
                    "name" => "Somalia ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "SO",
                    "query" => "",
                    "value" => "252",
                ],
                [
                    "name" => "South Africa",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "ZA",
                    "query" => "",
                    "value" => "27",
                ],
                [
                    "name" => "Spain ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "ES",
                    "query" => "",
                    "value" => "34",
                ],
                [
                    "name" => "Sri Lanka ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "LK",
                    "query" => "",
                    "value" => "94",
                ],
                [
                    "name" => "Sudan ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "SD",
                    "query" => "",
                    "value" => "249",
                ],
                [
                    "name" => "Suriname ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "SR",
                    "query" => "",
                    "value" => "597",
                ],
                [
                    "name" => "Swaziland",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "SZ",
                    "query" => "",
                    "value" => "268",
                ],
                [
                    "name" => "Sweden ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "SE",
                    "query" => "",
                    "value" => "46",
                ],
                [
                    "name" => "Switzerland ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "CH",
                    "query" => "",
                    "value" => "41",
                ],
                [
                    "name" => "Syria",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "SY",
                    "query" => "",
                    "value" => "963",
                ],
                [
                    "name" => "Taiwan ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "TW",
                    "query" => "",
                    "value" => "886",
                ],
                [
                    "name" => "Tajikistan ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "TJ",
                    "query" => "",
                    "value" => "992",
                ],
                [
                    "name" => "Tanzania",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "TZ",
                    "query" => "",
                    "value" => "255",
                ],
                [
                    "name" => "Thailand ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "TH",
                    "query" => "",
                    "value" => "66",
                ],
                [
                    "name" => "Tokelau ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "TK",
                    "query" => "",
                    "value" => "690",
                ],
                [
                    "name" => "Tonga",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "TO",
                    "query" => "",
                    "value" => "676",
                ],
                [
                    "name" => "Trinidad and Tobago ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "TT",
                    "query" => "",
                    "value" => "1868",
                ],
                [
                    "name" => "Tunisia ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "TN",
                    "query" => "",
                    "value" => "216",
                ],
                [
                    "name" => "Turkey ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "TR",
                    "query" => "",
                    "value" => "90",
                ],
                [
                    "name" => "Turkmenistan ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "TM",
                    "query" => "",
                    "value" => "993",
                ],
                [
                    "name" => "Turks and Caicos Islands ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "TC",
                    "query" => "",
                    "value" => "1649",
                ],
                [
                    "name" => "Tuvalu ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "TV",
                    "query" => "",
                    "value" => "688",
                ],
                [
                    "name" => "Uganda",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "UG",
                    "query" => "",
                    "value" => "256",
                ],
                [
                    "name" => "Ukraine",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "UA",
                    "query" => "",
                    "value" => "380",
                ],
                [
                    "name" => "United Arab Emirates",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "AE",
                    "query" => "",
                    "value" => "971",
                ],
                [
                    "name" => "United Kingdom ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "GB",
                    "query" => "",
                    "value" => "44",
                ],
                [
                    "name" => "Uruguay",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "UY",
                    "query" => "",
                    "value" => "598",
                ],
                [
                    "name" => "Uzbekistan",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "UZ",
                    "query" => "",
                    "value" => "998",
                ],
                [
                    "name" => "Vanuatu ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "VU",
                    "query" => "",
                    "value" => "678",
                ],
                [
                    "name" => "Vatican City State ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "VA",
                    "query" => "",
                    "value" => "418",
                ],
                [
                    "name" => "Venezuela ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "VE",
                    "query" => "",
                    "value" => "58",
                ],
                [
                    "name" => "Vietnam ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "VN",
                    "query" => "",
                    "value" => "84",
                ],
                [
                    "name" => "Virgin Islands, British ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "VI",
                    "query" => "",
                    "value" => "1284",
                ],
                [
                    "name" => "Virgin Islands, United States",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "VQ",
                    "query" => "",
                    "value" => "1340",
                ],
                [
                    "name" => "Wallis and Futuna Islands ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "WF",
                    "query" => "",
                    "value" => "681",
                ],
                [
                    "name" => "Yemen ",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "YE",
                    "query" => "",
                    "value" => "967",
                ],
                [
                    "name" => "Zambia",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "ZM",
                    "query" => "",
                    "value" => "260",
                ],
                [
                    "name" => "Zimbabwe",
                    "field" => "mobiles",
                    "operation" => "startsWith",
                    "short_name" => "ZW",
                    "query" => "",
                    "value" => "263",
                ]
            ]
        ];

        collect($filtersJson)->map(function ($value, $key) {
            $condition = Condition::where('name', $key)->first();
            $condition->filters()->createMany($value);
        });
    }
}
